server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anys34/Spring-Cloud-Config-Server
          search-paths: CloudConfigFile/**
          default-label: main